#!/usr/bin/env python3

import glob
import json
import os
import zlib


MASK = 0xFFFFF      # 20-bit hash for reference-style links
errors = 0

# romset to relative pathname
index = {
    '_note': 'Automatically generated by tools/update-index.py',
}
rootdir = os.path.join(os.path.dirname(__file__), '..')
names_to_map_ids = {}   # key is descriptive name of ROM, value is integer map ID
map_ids = {}            # key is integer map ID (hash of map pathname), value is map pathname
names_to_roms = {}      # key is descriptive name of ROM, value is PinMAME romset

# make sure ROMs listed in maps appear in romnames.json
with open(os.path.join(rootdir, 'romnames.json')) as f:
    romnames = json.load(f)

maps = os.path.join(rootdir, 'maps', '**', '*.map.json')
for map_file in glob.glob(maps, recursive=True):
    with open(map_file, 'r') as f:
        map_json = json.load(f)
        metadata = map_json.get('_metadata', {})
        roms = metadata.get('roms')
        platform = metadata.get('platform')
        if not roms:
            errors += 1
            print("Error: %s is missing a _metadata.roms entry" % map_file)
        elif not platform:
            errors += 1
            print("Error: %s is missing a _metadata.platform entry" % map_file)
        elif not os.path.isfile(os.path.join(rootdir, 'platforms', platform + '.json')):
            errors += 1
            print("Error: %s is missing platform file %s" % (map_file, platform))
        else:
            for rom in roms:
                name = romnames.get(rom)
                if not name:
                    errors += 1
                    print("Error: %s (from %s) does not appear in romnames.json" % (rom, map_file))
                if index.get(rom):
                    errors += 1
                    print("Error: %s appears in %s and %s" % (rom, index[rom], map_file))
                path = os.path.relpath(map_file, rootdir)
                index[rom] = path
                if name in names_to_roms:
                    print("Warning: multiple ROMs named %s" % name)
                # Generate a 20-bit hash, incrementing on collisions.
                # Current dataset has 2 collisions with 16-bit hash.
                map_id = zlib.crc32(bytes(path, 'utf-8')) & MASK
                while map_ids.get(map_id, path) != path:
                    map_id = (map_id + 1) & MASK     # increment ID on collision
                map_ids[map_id] = path
                names_to_map_ids[name] = map_id
                names_to_roms[name] = rom

with open(os.path.join(rootdir, 'index.json'), 'w') as f:
    f.write(json.dumps(index, indent=2, sort_keys=True))
    f.write('\n')   # include trailing newline

with open(os.path.join(rootdir, 'maplist.md'), 'w') as f:
    map_paths = []
    for name, map_id in sorted(names_to_map_ids.items()):
        f.write('* [%s][%05x] _%s_\n' % (name, map_id, names_to_roms.get(name)))
    f.write('\n')
    for map_id, path in sorted(map_ids.items()):
        f.write('[%05x]: %s\n' % (map_id, path))

exit(errors)
