#!/bin/sh

# Regenerates `last-updated.json`, which records when the map data (any *.json
# file) last changed on the current branch, and where to download that exact
# revision.  Downstream projects that keep a local cache of this repository can
# poll that one small file to decide whether they need to refresh, instead of
# re-fetching everything.
#
# Normally run for you by .github/workflows/last-updated.yml; run it by hand to
# preview what that workflow would commit.

set -eu

ROOT=$(git rev-parse --show-toplevel)

# Repository slug, for building the archive URLs.  GitHub Actions provides
# GITHUB_REPOSITORY; fall back to the origin remote for local runs.
REPO=${GITHUB_REPOSITORY:-}
if [ -z "$REPO" ] ; then
    REPO=$(git -C "$ROOT" config --get remote.origin.url 2>/dev/null \
        | sed -e 's|^.*github\.com[:/]||' -e 's|\.git$||')
fi
if ! echo "$REPO" | grep -Eq '^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$' ; then
    echo "Error: could not determine the GitHub repository from remote.origin.url." >&2
    echo "       Set GITHUB_REPOSITORY=owner/name and try again." >&2
    exit 1
fi

# --first-parent dates a merged pull request by its merge commit rather than by
# whenever the contributor happened to commit, which keeps the timestamp
# monotonic -- what a downstream cache needs.  `last-updated.json` itself is
# excluded so that regenerating it never counts as a change to the map data.
# A bare `*.json` pathspec matches at any depth.
INFO=$(TZ=UTC git -C "$ROOT" log -1 --first-parent \
    --format='%H %ct %cd' --date=format-local:'%Y-%m-%dT%H:%M:%SZ' \
    -- '*.json' ':(exclude)last-updated.json')

if [ -z "$INFO" ] ; then
    echo "Error: no commit touching a *.json file found" >&2
    exit 1
fi

COMMIT=$(echo "$INFO" | cut -d' ' -f1)

# Same formatting as tools/reformat-json.sh, so the Validate workflow is happy.
# `jq -S` sorts `_note` first, matching index.json.
jq -Sn --indent 2 --ascii-output \
    --arg _note 'Automatically generated by tools/update-last-updated.sh' \
    --arg commit "$COMMIT" \
    --argjson last_updated "$(echo "$INFO" | cut -d' ' -f2)" \
    --arg last_updated_iso "$(echo "$INFO" | cut -d' ' -f3)" \
    --arg tarball_url "https://github.com/$REPO/archive/$COMMIT.tar.gz" \
    --arg zipball_url "https://github.com/$REPO/archive/$COMMIT.zip" \
    '$ARGS.named' > "$ROOT/last-updated.json"
